#Aqui somente o que é diferente do application.yml que é o ambiente dev
# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db.cbwiksw0tl7t.sa-east-1.rds.amazonaws.com:3306/realmeet?&serverTimezone=UTC&useSSL=false
    username: admin
    password: adminadmin