# =================================
# = Server
# =================================
server:
  port: 8080
  servlet:
    context-path: /v1   #  controle de versao

# =================================
# = Spring
# =================================
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/realmeet?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource # gerenciar conexoes em aberto
  mail: #envio de e-mail
    host: smtp.gmail.com
    username: a@a.com
    password: password
    from: a@a.com
    properties:
      mail.transport.protocol: smtp
      mail.smtp.port: 587
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


# =================================
# = Logging - INFO - TRACE - DEBUG - ERROR
# =================================
logging:
  level:
    org.springframework: ERROR
    org.flywaydb: ERROR

# =================================
# = RealMeet
# =================================
realmeet:
  allocations:
    maxFilterLimit: 50
  email:
    templates:
      allocationCreated:
        subject: Novo agendamento de sala criado
        templateName: allocation-created.html
      allocationUpdated:
        subject: Agendamento de sala alterado
        templateName: allocation-updated.html
      allocationDeleted:
        subject: Agendamento de sala excluído
        templateName: allocation-deleted.html
      allocationReport:
        subject: Relatório de agendamento de sala
        templateName: allocation-report.html
  reports:
    allocationReport:
      maxMonthsInterval: 24